version: 1
validation: sovereign
default_denom: stake
accounts:
  - name: alice
    coins:
      - 20000token
      - 200000000stake
  - name: bob
    coins:
      - 10000token
      - 100000000stake
  - name: charlie
    coins:
      - 150000token
      - 100000000stake
  - name: david
    coins:
      - 50000token
      - 100000000stake
  - name: ellen
    coins:
      - 77000token
      - 100000000stake
  - name: frank
    coins:
      - 85000token
      - 100000000stake
  - name: george
    coins:
      - 40000token
      - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 5token
    - 100000stake
validators:
  - name: alice
    bonded: 100000000stake
  - name: validator1
    bonded: 200000000stake
  - name: validator2
    bonded: 100000000stake
